### ISSUE TITLE
Stochastic linearization produces unbound variables.

### ISSUE THREAD

**Issue by wiegerw** [mCRL2org/mCRL2#1535] opened 2019-06-03 14:03 UTC
When linearizing the process below, an LPS is generated with an unbound variable x1.

```
act
  a,c,b,d;

init
  dist x0: Bool[1/2].(x0 -> (a . dist x1: Bool[1/2].(x1 -> a)));
```

**Comment by jgroote** [comment] 2019-06-08 15:24
This was caused by forgetting to add the bound variables in a distribution operator to the set of free variables belonging to the argument of the distribution operator. This will be checked in after tests have been run.

**Comment by jgroote** [comment] 2019-06-13 20:13
This problem should be resolved now.

**Closed by jgroote** 2019-06-13 20:13 UTC
