### ISSUE TITLE
ltsconvert branching-bisim introduces spontaneous multi-action for Aldebaran file with hidden labels

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1786] opened 2024-10-03 14:36 UTC
For this .aut file the command ` ./stage/bin/ltsconvert -ebranching-bisim --tau=i input.aut output.aut` turns one action into a multi-action. This makes the action labels incomparable and can even change the order.

```
des (0, 2, 1)
(0, "RA !ADD (0, EMPTYSET) !+1 !+1", 0)
(0, i, 0)
```

```
des (0,1,1)
(0,"RA !ADD (0, EMPTYSET)| !+1 !+1",0)
```

**Comment by jgroote** [comment] 2024-11-01 08:16
The problem is not due to the option -ebranching-bisim. It also occurs without this flag.

**Comment by jgroote** [comment] 2024-11-02 10:28
The reason for the issue is that after the arguments of an action, indicated by the outermost closing bracket, it is assumed that an action ends and a new action starts. This caused the "|" to be inserted. In an upcoming commit the action will only be split in multi-actions if there are already "|" symbols present in the action. In an action of the form "a(args) blah" the "blah" part will be taken as belonging to the action before it, and only the "a" will be considered for hiding. If the "a" must be hidden, the whole action, including the argument and blah are renamed to tau.

**Comment by jgroote** [comment] 2024-11-02 14:26
Resolved in above mentioned commit.

**Closed by jgroote** 2024-11-02 14:26 UTC
Labels: bug
