### ISSUE TITLE
multi-actions are not (always) normalized internally, e.g. before comparison in ltscompare

### ISSUE THREAD

**Issue by gjveltink** [mCRL2org/mCRL2#1595] opened 2020-05-01 13:38 UTC
The order of the actions that make up a multi-action are not always properly normalized within the mcrl2 tool set. I have not been able to reproduce this problem with a (very) small example, so this behaviour seems to be spurious.

Attached are two files that specify the behaviour of a simple crossing with four traffic lights.
These specifications should be bbsimilar, but ltscompare thinks they aren't because the first file initially offers the following multi-action:
- show(west, red)|show(south, red)|show(east, red)|show(north, red)
whereas, the second file initially offers the following multi-action:
- show(west, red)|show(east, red)|show(south, red)|show(north, red)

It is clear that only the order of the actions within the multi-action are different, which shouldn't be a problem for equality!

The problem seems to stem from the fact, that the order of the processes within the definitions of the parallel composition are different:
- 	Crossing =  TrafficLight(north, red) || TrafficLight(east, red) || TrafficLight(south, red) || TrafficLight(west, red);
vs.
- 	TrafficLight = TF(north,red) || TF(south,red) || TF(east,red) || TF(west,red);

Personally I would expect some kind of normalization of the order within the multi-action for both(!) e.g. alphabetically, like:
- show(east, red)|show(north, red)|show(south, red)|show(west, red)

Please inform!

Apparently, a file ending in ".mcrl2" cannot be attached here.
I have added ".txt" just to be able to upload!

[TrafficLights_spec.mcrl2.txt](https://github.com/mCRL2org/mCRL2/files/4564370/TrafficLights_spec.mcrl2.txt)

[TrafficLights_v1.mcrl2.txt](https://github.com/mCRL2org/mCRL2/files/4564381/TrafficLights_v1.mcrl2.txt)

**Comment by tneele** [comment] 2020-05-01 14:35
This problem only seems to occur when multiple actions with the same name, but different data parameters occur in a different order. I have managed to reduce the example to the following two processes:
```
act a:Bool;

init a(true)|a(false).delta;
```
and
```
act a:Bool;

init a(false)|a(true).delta;
```
Save these processes in files `a.mcrl2` and `b.mcrl2` and run
```
mcrl22lps a.mcrl2 a.lps
mcrl22lps b.mcrl2 b.lps
lps2lts a.lps a.lts
lps2lts b.lps b.lts
ltscompare -ebisim a.lts b.lts
```
The tool deems these LTSs not bisimilar, although they clearly are according to the axiom MA1 `a|b = b|a`. I expect that this is a bug in the routine that decides whether two multi-actions are equivalent.

**Comment by tneele** [comment] 2020-05-02 18:27
I have found another scenario in which this issue occurs. Consider the following specifications saved in `a.mcrl2` and `b.mcrl2`:
```
act a,b;
proc X = a|b.X;
init X;
```
```
act a,b;
proc X = b|a.X;
init X;
```
Now run
```
txt2lps a.mcrl2 a.lps
txt2lps b.mcrl2 b.lps
lps2lts a.lps a.lts
lps2lts b.lps b.lts
ltscompare -ebisim a.lts b.lts
```
The tool claims these LTSs are not equal. 

After investigation, my conclusion is that only in the lineariser, the actions in a multi-action are sorted, and only on action label. I think we should reconsider the API of the `multi_action` class, such that `multi_action({a, b}) == multi_action({b, a})`, where `a` and `b` are variables containing an action, always holds.

**Comment by wiegerw** [comment] 2020-05-04 08:22
I agree that adding a global invariant to `multi_action` will probably solve this issue. But to me the issue suggests that there is an error in ltscompare, and I would find it much more logical that the issue is solved there.

Note that adding this invariant to `multi_action` will not just affect the constructor. The function `action_list& multi_action::actions()` has hundreds of usages that would need to be inspected.

**Comment by tneele** [comment] 2020-05-04 10:23
Some more findings from my investigation: none of the ltscompare algorithms actually deal with (multi-)actions, they only reason about the indices of multi-actions. The problem originates in the merging of LTSs that happens prior to comparison. At that point, `a(true)|a(false)` and `a(false)|a(true)` are stored as two different actions.

We can fix this specific issue by sorting the actions within a multi-action in the merge-LTS algorithm. I am in favour of a more rigorous solution, where the `multi_action` class enforces the sorting, to prevent similar issues in the future. We can start by changing the constructor, and leave the `action_list& multi_action::actions()` for later, or do both at once.

**Comment by wiegerw** [comment] 2020-05-04 12:31
I still don't see why this solution is preferable over fixing the merge-LTS algorithm. There are many data types in mCRL2 that store items in an unsorted list, where they could be sorted without changing the semantics. Is there a reason that `multi_action` needs special treatment?

**Comment by Valo13** [comment] 2020-05-04 13:00
I'm probably not familiar enough with the libraries, but would it be a good (general) solution to define the equality operator `==` for multiactions (such that `multi_action({a, b}) == multi_action({b, a})`)?
Merge-LTS can then be fixed by "merging" multiactions that are equal according to `==`.

**Comment by jgroote** [comment] 2020-05-04 13:05
This is a serious problem that requires a solution, although it does not very often turn out to occur. 
Maybe because multi-actions are not that popular.

I can imagine that we solve this by making it a responsibility of the lts library.

Whenever the lts library provides a multi action, it must be well ordered.

Whenever multi-actions are output in .aut or .fsm format the action labels must be well
ordered.

One question is what the natural ordering should be. If that is determined, I can implement it.

Jan Friso 



> On 4 May 2020, at 15:00, Olav Bunte <notifications@github.com> wrote:
> 
> 
> I'm probably not familiar enough with the libraries, but would it be a good (general) solution to define the equality operator == for multiactions (such that multi_action({a, b}) == multi_action({b, a}))?
> Merge-LTS can then be fixed by "merging" multiactions that are equal according to ==.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Closed** 2020-05-16 21:08 UTC
Labels: bug
