### ISSUE TITLE
Segmentation fault pbessolvesymbolic

### ISSUE THREAD

**Issue by markuzzz** [mCRL2org/mCRL2#1660] opened 2021-11-05 12:36 UTC
I use a portfolio solving technique to check formulas. In paralll I run i) pbessymbolicsolve on a PBES generated from the LPS, and ii) pbessolve on a PBES generated from the LTS. 

For one of my formulas I got a different result. pbessymbolicsolve gives the result 'false', pbessolve gives the result 'true'. I am reasonably certain that the result should be 'true'. Attached you will find a ZIP with the mCRL2 model, the mu-calculus formula and a script that reproduces the issue.
[Reproduce bug.zip](https://github.com/mCRL2org/mCRL2/files/7485989/Reproduce.bug.zip)

I am using a nightly build from one or two months ago.

**Comment by twillems** [comment] 2021-11-05 15:40
I can no longer reproduce this using the revision I have running on my laptop (commit ce8cf9f00):

[16:27:25] --- parity game information ---
[16:27:25] priority 0: there are 1 vertices.
[16:27:25] priority 1: there are 5.39142e+08 vertices.
[16:27:25] priority 2: there are 1.30266e+08 vertices.
[16:27:25] there are 6.69408e+08 even vertices and 1 odd vertices.
[16:33:29] finished solving (time = 312.84s)
true

I am aware of a few bugs that have been squashed (in particular with the optimisations -s1 and -s2) a bit less than a month ago, so it would be good to check whether you are still running into issues with the current nightly. If so, we should investigate.

Best wishes,
Tim

________________________________________
From: markuzzz ***@***.***>
Sent: 05 November 2021 13:36
To: mCRL2org/mCRL2
Cc: Subscribed
Subject: [mCRL2org/mCRL2] Different result pbessymbolicsolve and explicit state tools (Issue #1660)

I use a portfolio solving technique to check formulas. In paralll I run i) pbessymbolicsolve on a PBES generated from the LPS, and ii) pbessolve on a PBES generated from the LTS.

For one of my formulas I got a different result. pbessymbolicsolve gives the result 'false', pbessolve gives the result 'true'. I am reasonably certain that the result should be 'true'. Attached you will find a ZIP with the mCRL2 model, the mu-calculus formula and a script that reproduces the issue.
Reproduce bug.zip<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmCRL2org%2FmCRL2%2Ffiles%2F7485989%2FReproduce.bug.zip&data=04%7C01%7C%7C82e5766d8304409e58d308d9a058f6e4%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C1%7C637717126225041112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=49AA5n3J7Z9QXSxEomAeSuHmr83hzDfvrZMi%2Fj%2FLlmM%3D&reserved=0>

I am using a nightly build from one or two months ago.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmCRL2org%2FmCRL2%2Fissues%2F1660&data=04%7C01%7C%7C82e5766d8304409e58d308d9a058f6e4%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C1%7C637717126225051110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dXNIwEeB4ZXesVOADSThuyRNw40fuX%2FKV1VZDdPFWVY%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAI7VLLHI5BRNQRIPIZS2A3UKPFWXANCNFSM5HNX5PNQ&data=04%7C01%7C%7C82e5766d8304409e58d308d9a058f6e4%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C1%7C637717126225061104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hkao%2FeiGKukMHwEaiNETKxrAarthNAJQk9LoYrbYawM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C82e5766d8304409e58d308d9a058f6e4%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C1%7C637717126225061104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nKfF3WX%2Fo8rpaS7W29hFTgzgSPvtC92apdKVh4hNtHU%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C82e5766d8304409e58d308d9a058f6e4%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C1%7C637717126225071098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lKhiU45CEnUfgAttRA1oh6%2FMgPz%2FF2IViua%2FLPh0H%2Bc%3D&reserved=0>.

**Comment by markuzzz** [comment] 2021-11-08 10:38
Hi Tim, updating to the most recent version (the same commit you used) has resolved the issue. However, I sometimes get a segmentation fault. The segmentation fault only occurs for some formulas and seems to be resolved completely when not using the -s2 optimization.

**Comment by mlaveaux** [comment] 2021-11-08 11:47
If you have an example that causes a segmentation fault then I can look into it.

**Comment by markuzzz** [comment] 2021-11-08 12:55
[Archive.zip](https://github.com/mCRL2org/mCRL2/files/7497055/Archive.zip)

**Comment by markuzzz** [comment] 2021-11-08 12:56
The example I just posted creates a segmentation fault on the Mastodont but works fine on my laptop. Removing the -s2 flag fixes the issue on the Mastodont. Both are running the latest mCRL2 version.

**Comment by markuzzz** [comment] 2021-11-08 12:58
I have run it multiple times on both machines so there doesn't seem to be a form of non-determinism. The stack size is already set to "unlimited". Perhaps you can run it on the Mastodont with your mCRL2 installation.

**Comment by mlaveaux** [comment] 2021-11-15 13:01
An update on this issue. I am indeed able to reproduce the crash on the mastodont with the given example. Unfortunately, it also works fine on my laptop. The segmentation fault happens inside the Sylvan library during garbage collection (as far as I can tell). It seems that increasing the memory limit avoids the issue. Finally, the issue does not occur on the mastodont when compiling the toolset with Clang instead of GCC. Therefore, a (rather unsatisfying) solution is to compile the toolset with Clang for now.

I will keep this issue open since it must be dealt with properly before the next release, but I have not found a solution yet.

**Comment by mlaveaux** [comment] 2022-02-16 14:07
I have finally committed a fix for this issue after delving further into the Sylvan library (where the issue was actually located) and can no longer reproduce the issue for the given example. Note that the option -s2 has become -s3 after a more recent commit, but both options now work fine.

**Closed** 2022-02-18 09:09 UTC
Labels: bug
