### ISSUE TITLE
Problem with IDE over Windows 10

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1624] opened 2020-08-31 12:54 UTC
IDE is unable to create a new project. By clicking the create button, nothing happens.  
I am using mCRL2 toolset 202006.0 (Release)
over Window 10 Pro
I tried to open old projects, they are converted to the new version and work fine.

**Comment by Valo13** [comment] 2020-08-31 12:58
I cannot reproduce this on Windows 10. A file window should appear whenever you click new project. Are you sure there isn't one opened in the background?

**Comment by matifch** [comment] 2020-08-31 13:14
Nothing was opened in background. Even I tried with restarting Windows. I am sending a small video to demonstrate the error where you can see that clicking the "create" button does not allow to go ahead. 
[errorreport.pptx](https://github.com/mCRL2org/mCRL2/files/5150399/errorreport.pptx)

**Comment by tneele** [comment] 2020-08-31 14:02
You have to type a name in the 'project name' text field to create a new project.

**Comment by Valo13** [comment] 2020-08-31 15:26
Like @tneele says, whenever you create a new project you need to give it a name. This is done by filling in the field following "Project name:" that can be found below the file view.

**Comment by jgroote** [comment] 2020-08-31 15:32
If people get confused by the behaviour of the tool when leaving the name blanc,
should there be some action by mcrl2ide to avoid the confusion, such as a warning,
or a default grey text "Fill in project name"?


> On 31 Aug 2020, at 17:26, Olav Bunte <notifications@github.com> wrote:
> 
> 
> Like @tneele says, whenever you create a new project you need to give it a name. This is done by filling in the field following "Project name:" that can be found below the file view.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

____________________________________________________________________________________
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by Valo13** [comment] 2020-08-31 15:34
mCRL2IDE uses the native (in this case Windows) file dialog, so I'm not sure this can be done

**Comment by Valo13** [comment] 2020-11-19 16:29
After some more research this really seems to be default behaviour of the Windows file dialog. The only way I could change this is by making a file dialog myself instead of using native file dialogs, but I think that using native file dialogs is important for the usability, so I'll close this issue.

**Closed by Valo13** 2020-11-19 16:29 UTC
